In [1]:
import numpy as np

In [2]:
# 4.1
u = np.full((9, ), 2)
u

array([2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
# 4.2
liste = [8, 7, 6, 5, 4, 3, 2, 1, 0]
v = np.array(liste)
v.dtype

dtype('int64')

In [4]:
# 4.3
v[2] = 1
v

array([8, 7, 1, 5, 4, 3, 2, 1, 0])

In [5]:
# 4.4
prod = u * v
prod

array([16, 14,  2, 10,  8,  6,  4,  2,  0])

In [6]:
# 4.5
m = v.reshape(3, 3)
m

array([[8, 7, 1],
       [5, 4, 3],
       [2, 1, 0]])

In [7]:
# 4.6
n = m + 2.4
print(n)
print(m.dtype)
print(n.dtype)

[[10.4  9.4  3.4]
 [ 7.4  6.4  5.4]
 [ 4.4  3.4  2.4]]
int64
float64


In [8]:
# 4.7
sum_n = np.sum(n) 
sum_n

np.float64(52.6)